# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    groups:
      npm:
        patterns:
          - '*'
    directory: '/'
    schedule:
      interval: "daily"
    ignore:
      # Major upgrade not yet supported by all packages
      - dependency-name: eslint
        versions:
          - '^9.0.0'
      - dependency-name: eslint-plugin-unused-imports
        versions:
          - '^4.0.0'
    labels:
      - "patch"