name: Get PR labels
description: >
  This actions looks for any release labels such as: patch, minor, major, no-release.
  It will fail it no labels are found.

inputs:
  token:
    description: A GitHub token
    required: true
  repository:
    description: The repository to use
    required: false
    default: ${{ github.repository }}
  pull-number:
    description: The PR number
    required: false
    default: ${{ github.event.pull_request.number }}

outputs:
  release-label:
    description: The label found
  continue-release:
    description: True if the release can continue

runs:
  using: node20
  main: index.mts
