name: Get changed directories
description: >
  Uses git diff to find the list of changed directories, 
  compared to a previous commit SHA.

inputs:
  base-sha:
    description: The base commit SHA
    required: true
  ignore-if-all-deletions:
    description: If true, ignore entries where there have been only deletions
    required: false
    default: 'false'
  regex:
    description: A regex used to evaluate directory paths
    required: false
  max-depth:
    description: The max path depth to which aggregate directory names
    required: false
    default: '0'

outputs:
  matrix:
    description: The JSON matrix containing the list of changed directories
  matrix-empty:
    description: >
      "true" if the matrix is empty

runs:
  using: node20
  main: dist/index.mjs
