name: Initialize git user info
description: Sets the user name and email for git to use. Defaults to a GitHub actions user.
inputs:
  name:
    description: 'The user name'
    required: false
    default: 'github-actions[bot]'
  email:
    description: 'The user email'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
runs:
  using: "composite"
  steps:
    - name: Init git user
      shell: bash
      run: |
        git config user.name "$USER_NAME"
        git config user.email "$USER_EMAIL"
      env:
        USER_NAME: ${{ inputs.name }}
        USER_EMAIL: ${{ inputs.email }}