#!/usr/bin/env bash
#
# Copyright (c) 2024. Alberto Marchetti [ https://www.linkedin.com/in/albertomarchetti/ ]
#

set -euo pipefail

#
# Copyright (c) 2024. Alberto Marchetti [ https://www.linkedin.com/in/albertomarchetti/ ]
#

actionlint

npm run gen:docs
git add README.md

npm run gen:workflows
git add .github/workflows/*