#!/usr/bin/env bash
#
# Copyright (c) 2024. Alberto Marchetti [ https://www.linkedin.com/in/albertomarchetti/ ]
#

set -euo pipefail

#
# Copyright (c) 2024. Alberto Marchetti [ https://www.linkedin.com/in/albertomarchetti/ ]
#

actionlint

npm run gen
git add README.md
git add .github/workflows/*