name: Build the actions library

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - closed
      # Triggers the workflow when labels change in the PR
      - labeled
      - unlabeled

jobs:
  test:
    if: >
      github.event.action != 'closed' ||
      (github.event.action == 'closed' && github.event.pull_request.merged)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
      - shell: bash
        run: npm ci
      - shell: bash
        run: npm run test

  get-changes:
    if: >
      github.event.action != 'closed' ||
      (github.event.action == 'closed' && github.event.pull_request.merged)
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-changed-dirs.outputs.matrix }}
      matrix-empty: ${{ steps.get-changed-dirs.outputs.matrix-empty }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
      - shell: bash
        run: npm ci

      - id: get-changed-dirs
        uses: ./actions/action-get-changed-dirs
        with:
          base-sha: ${{ github.event.pull_request.base.sha }}
          max-depth: 1
          regex: ^actions/
          ignore-if-all-deletions: true

  build:
    needs:
      - test
      - get-changes
    runs-on: ubuntu-latest
    if: needs.get-changes.outputs.matrix-empty != 'true'
    permissions:
      pull-requests: read
      contents: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.get-changes.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/action-git-init-userinfo
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
      - shell: bash
        run: npm ci

      - name: Build
        id: build
        shell: bash
        run: >
          npx tsx ./lib/bin/build.mts
          --promote
          --token "$TOKEN"
          --repository "$GITHUB_REPOSITORY"
          --pullNumber "$PR_NUMBER"
          --release "$RELEASE"
          "$MATRIX_DIRECTORY"
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MATRIX_DIRECTORY: ${{ matrix.directory }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          RELEASE: ${{ github.event.action == 'closed' && github.event.pull_request.merged }}

      - uses: cloudposse/github-action-matrix-outputs-write@v1
        with:
          matrix-step-name: build
          matrix-key: ${{ matrix.directory }}
          outputs: |-
            version-branch: ${{ steps.build.outputs.version-branch }}

  # Trigger any test workflows after everything has been built
  post-build-test:
    needs:
      - get-changes
      - build
    runs-on: ubuntu-latest
    if: needs.get-changes.outputs.matrix-empty != 'true'
    permissions:
      pull-requests: read
      contents: write
      actions: write
    strategy:
      matrix: ${{ fromJSON(needs.get-changes.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: cloudposse/github-action-matrix-outputs-read@v1
        id: read-build-output
        with:
          matrix-step-name: build
      - run: echo "$JSON" | jq
        env:
          JSON: ${{ steps.read-build-output.outputs.result }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
      - shell: bash
        run: npm ci

      - name: Post build test
        shell: bash
        run: >
          npx tsx ./lib/bin/post-build-test.mts
          --token "$TOKEN"
          --repository "$GITHUB_REPOSITORY"
          --versionBranch "$VERSION_BRANCH"
          --headRef "$GITHUB_HEAD_REF"
          --release "$RELEASE"
          "$MATRIX_DIRECTORY"
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MATRIX_DIRECTORY: ${{ matrix.directory }}
          VERSION_BRANCH: ${{ fromJson(steps.read-build-output.outputs.result).version-branch[matrix.directory] }}
          RELEASE: ${{ github.event.action == 'closed' && github.event.pull_request.merged }}

  cleanup:
    needs:
      - get-changes
    runs-on: ubuntu-latest
    if: >
      needs.get-changes.outputs.matrix-empty != 'true' && 
      github.event.action == 'closed'
    permissions:
      pull-requests: read
      contents: write
    strategy:
      matrix: ${{ fromJSON(needs.get-changes.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
      - shell: bash
        run: npm ci

      - name: Cleanup
        shell: bash
        run: >
          npx tsx ./lib/bin/cleanup.mts
          --token "$TOKEN"
          --repository "$GITHUB_REPOSITORY"
          --pullNumber "$PR_NUMBER"
          "$MATRIX_DIRECTORY"
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MATRIX_DIRECTORY: ${{ matrix.directory }}
          PR_NUMBER: ${{ github.event.pull_request.number }}