name: Check release labels

on:
  pull_request:
    branches:
      - main

    # Trigger this workflow on events which could cause the
    # PR to have no labels
    types:
      - opened
      - unlabeled

jobs:
  # Verifies the presence of release labels when the PR
  # is opened or labels have changes
  check-labels:
    uses: ./.github/workflows/tpl-wf-build-check-labels-only.yml
    permissions:
      pull-requests: read
      contents: read