name: CI - Build on PR

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - closed
      # Triggers the workflow when labels change in the PR
      - labeled

jobs:
  build:
    uses: ./.github/workflows/ci-build.yml
    permissions:
      # Required to create new version branches
      contents: write
      # Required to publish comments on the PR
      pull-requests: write
      # Required to trigger test workflows via workflow_dispatch
      actions: write
      # Required to create commit statuses to mark the
      # execution of test workflows
      statuses: write
    with:
      # You can customize various commands
      test-command: npm run test:ci

      # If you want to disable linting
      # lint-command: echo NOOP

      # Or you can completely disable testing, in case you want to run your
      # own test suites before running the actions/workflows build pipeline.
      # skip-test: true

    secrets:
      # Provide a PAT to enable auto-generation of the
      # catch-all test workflow
      token-push-workflows: ${{ secrets.CI_BUILD_TOKEN_WORKFLOWS }}
