name: CI - Build on PR

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - closed
      # Triggers the workflow when labels change in the PR
      - labeled

jobs:
  build:
    uses: ./.github/workflows/ci-build.yml
    permissions:
      pull-requests: write
      contents: write
      actions: write
      statuses: write
    with:
      test-command: npm run test:ci
