# This workflow need to be invoked by any test workflow, after all other jobs
# are completed.
name: CI - After test / Finalize status checks

on:
  workflow_call:
    inputs:
      ctx:
        description: Pass inputs.ctx to this input
        required: true
        type: string
      needs-json:
        description: Pass toJSON(needs) to this input
        required: true
        type: string

jobs:
  finalize-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/github-script@v7
        env:
          CI_CTX_JSON: ${{ inputs.ctx }}
          NEEDS_JSON: ${{ inputs.needs-json }}
        with:
          script: |
            const { 
              CI_CTX_JSON, 
              NEEDS_JSON, 
              HEAD_SHA,
            } = process.env;
            if (CI_CTX_JSON == null) {
              throw new Error('ctx input not found.');
            }
            if (NEEDS_JSON == null) {
              throw new Error('needs-json input not found.');
            }

            const ctx = JSON.parse(CI_CTX_JSON);

            // Find at least one failed job in the "needs" context
            const needs = JSON.parse(NEEDS_JSON);
            const anyFailed = Object.entries(needs)
              .find(([k,v]) => v.result == 'failure') != null;

            const url = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`; 

            // Finalize the status for the workflow
            await gh.octokit.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ctx.statusName,
              state: anyFailed ? 'failure' : 'success',
              sha: headSHA,
              target_url: url,
            });
