# This workflow need to be invoked by any test workflow, after all other jobs
# are completed.
name: CI - After test / Finalize status checks

on:
  workflow_call:
    inputs:
      needs-json:
        description: Pass toJSON(needs) to this input
        required: true
        type: string

jobs:
  finalize-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/github-script@v7
        env:
          JSON: ${{ inputs.needs-json }}
        with:
          script: |
            const util = require('node:util');

            if (process.env.JSON == null) {
              throw new Error('needs-json input not found.');
            }
            // Find at least one failed job in the "needs" context
            const needs = JSON.parse(process.env.JSON);
            const anyFailed = Object.entries(needs)
              .find(([k,v]) => v.result == 'failure') != null;

            console.log('Context: ' + util.inspect(context, {depth:null}))

            // cmaster11/gha/.github/workflows/test.yml@refs/heads/main
            // cmaster11/gha/.github/workflows/test.yml
            // test.yml
            const name = context.payload.workflow_ref.split('@')[0].split('/').reverse()[0];

            // Finalize the status check for the workflow
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name,
              status: 'completed',
              conclusion: anyFailed ? 'failure' : 'success',
            })
