name: Check PR release labels
on:
  workflow_call: {}

jobs:
  get-release-label:
    name: Get release label
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
      - shell: bash
        run: npm ci

      - run: npx tsx ./lib/ci/ci-build-actions.ts --inline action-ci-build
      - name: Get release label
        id: get-release-label
        uses: ./tmp-inline/action-ci-build
        with:
          phase: get-release-label
          token: ${{ secrets.GITHUB_TOKEN }}
