name: Test action-example
on:
  workflow_call: { inputs: { test-ctx: { type: string } } }

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: '${{ fromJSON(inputs.test-ctx).ref }}'

      # Run the action to test it
      - id: action
        uses: ./
        with:
          greeting: Hello world!

      # Dump the outputs
      - run: |
          echo "$JSON" | jq '.'
        env:
          JSON: ${{ toJSON(steps.action) }}
