name: Test workflow-create-release

on:
  workflow_dispatch: { inputs: { ctx: {} } }
  # Register the workflow so that it can be triggered
  # via workflow_dispatch event
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test-workflow-create-release.yml

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: test-release-dist
          path: __testing__/workflow-create-release/
          retention-days: 1
          if-no-files-found: error

  create-release:
    permissions:
      contents: write
    needs: create-artifact
    uses: ./.github/workflows/workflow-create-release.yml
    with:
      artifact-name: test-release-dist
      release-branch: test-workflow-create-release-release
      release-tag-prefix: test-workflow-create-release-release
