name: Test workflow-create-release

on:
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/test-workflow-create-release.yaml # self
      - .github/workflows/workflow-create-release.yaml
      - __testing__/workflow-create-release

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v4
        with:
          name: test-release-dist
          path: __testing__/workflow-create-release
          retention-days: 1

  create-release:
    needs: create-artifact
    uses: ./.github/workflows/workflow-create-release.yaml
    with:
      artifact-name: test-release-dist
      release-branch: test-workflow-create-release-release