name: Test workflow-test

on:
  workflow_dispatch: { inputs: { ctx: {} } }
  # Register the workflow so that it can be triggered
  # via workflow_dispatch event
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test-workflow-test.yml

jobs:
  test:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/workflow-test.yml

  ci-after-test:
    needs:
      - test
    if: always() && github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/ci-post-build-after-test.yml
    permissions:
      statuses: write
    with:
      ctx: ${{ inputs.ctx }}
      needs-json: ${{ toJSON(needs) }}
