name: Test action-get-changed-dirs
on:
  workflow_call: { inputs: { test-ctx: { type: string } } }

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: '${{ fromJSON(inputs.test-ctx).ref }}'

      # Run the action to test it
      - id: action
        uses: ./
        with:
          base-sha: HEAD~1

      # Dump the outputs
      - run: |
          echo "$JSON" | jq '.'
        env:
          JSON: ${{ toJSON(steps.action) }}
