name: Test action-get-release-label
on:
  workflow_call: { inputs: { test-ctx: { type: string } } }

jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: read
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: '${{ fromJSON(inputs.test-ctx).ref }}'

      - id: action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-number: 6

      - run: |
          echo "$JSON" | jq '.'
        env:
          JSON: ${{ toJSON(steps.action) }}
