name: Test wf-test

on:
  workflow_call: { inputs: { test-ctx: { type: string } } }

jobs:
  test:
    # Invoke the reusable workflow
    uses: ./.github/workflows/wf-test.yml

  dump:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Dump the result of the workflow
        run: |
          echo "$JSON" | jq '.'
        env:
          JSON: ${{ toJSON(needs.test) }}
