name: Test action-ci-build
on:
  workflow_call: { inputs: { test-ctx: { type: string } } }

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: npm ci

      - uses: actions/checkout@v4
        with:
          path: checkout/action-ci-build
          ref: '${{ fromJSON(inputs.test-ctx).ref }}'

      # Build the action
      - id: action
        uses: ./checkout/action-ci-build
        with:
          phase: test-action-ci-build
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-number: ${{ fromJSON(inputs.test-ctx).pullNumber }}
          working-directory: __testing__/action-ci-build

      # Dump the outputs
      - run: |
          echo "$JSON" | jq '.'
        env:
          JSON: ${{ toJSON(steps.action) }}

      # Run the test action
      - id: test-action
        uses: ./__testing__/action-ci-build/tmp-inline/test-action

      # Dump the outputs
      - run: |
          echo "$JSON" | jq '.'
        env:
          JSON: ${{ toJSON(steps.test-action) }}
