name: Test action-get-release-label
on:
  workflow_dispatch: { inputs: { ctx: {} } }
  # Register the workflow so that it can be triggered
  # via workflow_dispatch event
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test-action-get-release-label.yml
jobs:
  test:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: read
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: '${{ fromJSON(inputs.ctx).ref }}'

      - id: action-get-release-label
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-number: 6

      - run: |
          echo "$JSON" | jq '.'
        env:
          JSON: ${{ toJSON(steps.action-get-release-label) }}

  # Notify GitHub about the result of the test
  ci-after-test:
    needs:
      - test
    if: always() && github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/ci-post-build-after-test.yml
    permissions:
      checks: write
    with:
      ctx: ${{ inputs.ctx }}
      needs-json: ${{ toJSON(needs) }}
