name: Test action-test

on:
  workflow_dispatch: { inputs: { ref: { required: true } } }
  # Register the workflow
  pull_request:
    branches: [main]
    paths: [.github/workflows/test-action-test.yml]

jobs:
  test:
    name: Test action-test
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - id: action-test
        uses: ./
        with:
          greeting: Hello world!
      - run: |
          echo "$JSON" | jq '.'
        env:
          JSON: ${{ toJSON(steps.action-test) }}

  after-test:
    needs:
      - test
    if: always() && github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/ci-post-build-after-test.yml
    secrets: inherit
    with:
      needs-json: ${{ toJSON(needs) }}
