name: Test action-test
on:
  workflow_dispatch:
    inputs:
      ref:
        description: The ref of the commit to clone
        required: true
  # Register the workflow so that it can be triggered
  # via workflow_dispatch event
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test-action-test.yml

jobs:
  test:
    name: Test action-test
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - id: action-test
        uses: ./
        with:
          greeting: Hello world!

      - run: |
          echo "$JSON" | jq '.'
        env:
          JSON: ${{ toJSON(steps.action-test) }}

  ci-after-test:
    needs:
      - test
    if: always() && github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/ci-post-build-after-test.yml
    permissions:
      checks: write
    with:
      needs-json: ${{ toJSON(needs) }}
