name: Test action-get-release-label

on:
  workflow_dispatch: { inputs: { ref: { required: true } } }
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/test-action-get-release-label.yml # self
      - actions/action-get-release-label

jobs:
  test-action-get-release-label:
    name: Test action-get-release-label
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: read
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - id: action-get-release-label
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-number: 6
      - run: |
          echo "$JSON" | jq '.'
        env:
          JSON: ${{ toJSON(steps.action-get-release-label) }}