name: Test action-test
on:
  workflow_call: { inputs: { test-ctx: { type: string } } }

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the dev branch
        uses: actions/checkout@v4
        with:
          ref: '${{ fromJSON(inputs.test-ctx).ref }}'

      - name: Run the action
        id: action
        uses: ./
        with:
          greeting: Hello world!

      - name: Dump the result of the action
        run: |
          echo "$JSON" | jq '.'
        env:
          JSON: ${{ toJSON(steps.action) }}
