name: Test action-example
on:
  workflow_dispatch:
    inputs:
      ref:
        description: The ref of the commit to clone
        required: true
  # Register the workflow so that it can be triggered
  # via workflow_dispatch event
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test-action-example.yml

jobs:
  test:
    name: Test action-example
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      # Run the action to test it
      - id: action-example
        uses: ./
        with:
          greeting: Hello world!

      # Dump the outputs
      - run: |
          echo "$JSON" | jq '.'
        env:
          JSON: ${{ toJSON(steps.action-example) }}

  # Notify GitHub about the result of the test
  ci-after-test:
    needs:
      - test
    if: always() && github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/ci-post-build-after-test.yml
    permissions:
      checks: write
    with:
      needs-json: ${{ toJSON(needs) }}
