name: Test action-test

on:
  workflow_dispatch: { inputs: { ref: { required: true } } }
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/test-action-test.yml # self
      - actions/action-test

jobs:
  test-action-test:
    name: Test action-test
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - id: action-test
        uses: ./
        with:
          greeting: Hello world!
      - run: |
          echo "$JSON" | jq '.'
        env:
          JSON: ${{ toJSON(steps.action-test) }}
