name: Test wf-create-release

on:
  workflow_call: { inputs: { test-ctx: { type: string } } }

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: test-release-dist
          path: __testing__/workflow-create-release/
          retention-days: 1
          if-no-files-found: error

  create-release:
    permissions:
      contents: write
    needs: create-artifact
    uses: ./.github/workflows/wf-create-release.yml
    with:
      artifact-name: test-release-dist
      release-branch: test-wf-create-release-release
      release-tag-prefix: test-wf-create-release-release
