name: Test action-ci-build
on:
  workflow_call: { inputs: { test-ctx: { type: string } } }

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: '${{ fromJSON(inputs.test-ctx).ref }}'

      # Create a fake action
      - run: |
          mkdir -p actions/test-action
          cd actions/test-action

          npm init -y
          npm install --save-dev @actions/github @actions/core
          cat << EOF > action.yml
          name: test-action
          runs:
            using: node20
            main: index.ts
          EOF
          cat << EOF > index.ts
          import { setOutput } from '@actions/core';
          import { context } from '@actions/github';
          console.log('Context', JSON.stringify(context));
          setOutput('hey', 'Yeah!');
          EOF

      # Build the action
      - id: action
        uses: ./
        with:
          phase: test-action-ci-build
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-number: ${{ fromJSON(inputs.test-ctx).pullNumber }}

      # Dump the outputs
      - run: |
          echo "$JSON" | jq '.'
        env:
          JSON: ${{ toJSON(steps.action) }}

      # Run the test action
      - id: test-action
        uses: ./actions/test-action

      # Dump the outputs
      - run: |
          echo "$JSON" | jq '.'
        env:
          JSON: ${{ toJSON(steps.test-action) }}
