name: A test workflow, used to test sub-workflows

on:
  workflow_call:

jobs:
  run-subworkflow:
    uses: ./.github/workflows/wf-test-subworkflows.another.yml

  echo:
    runs-on: ubuntu-latest
    needs: run-subworkflow
    steps:
      - run: |
          echo "Whoami: ${{ needs.run-subworkflow.outputs.whoami }}"
