name: Creates a release from an artifact into a standalone branch

on:
  workflow_call: 
    inputs:

      artifact-name:
        description: The name of the artifact containing all the files we want to put in the release
        type: string
        required: true
        default: release-dist

      release-branch:
        description: The name of the branch in which to create the release
        type: string
        required: true
        default: release

      release-tag-prefix:
        description: The prefix of the release tag
        type: string
        required: true
        default: release

    outputs:
      tag:
        description: The tag of the new release
        value: ${{ jobs.create-release.outputs.tag }}

jobs:
  create-release:
    name: Create release
    outputs:
      tag: ${{ steps.create-release.outputs.tag }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git config --global pull.ff only

      - uses: actions/checkout@v4
        with:
          path: source-repo
      - name: Bootstrap the release branch
        run: |
          set -euo pipefail
          cd "${GITHUB_WORKSPACE}/source-repo"
          # Make sure the remote branch exists or bootstrap it
          TMP="$(mktemp -d)"
          cp -r .git "$TMP/"
          cd "$TMP"
          git fetch
          git switch -c "$RELEASE_BRANCH"
          git branch --set-upstream-to=origin/"$RELEASE_BRANCH" "$RELEASE_BRANCH" && { exit 0; }
          git add .
          git commit -m "First empty commit"
          git push --set-upstream origin "$RELEASE_BRANCH"
        env:
          RELEASE_BRANCH: ${{ inputs.release-branch }}

      - name: Download the release artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: release-artifact

      - name: Checkout the release branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release-branch }}
          path: release-branch
      - id: create-release
        run: |
          set -euo pipefail
          
          tag="${RELEASE_TAG_PREFIX}-${GITHUB_SHA}"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          
          artifactDir="${GITHUB_WORKSPACE}/release-artifact"
          branchDir="${GITHUB_WORKSPACE}/release-branch"

          cp -r "${artifactDir}"/* "${branchDir}/"

          cd "${branchDir}"
          git add .
          git commit -m "$tag" --allow-empty
          git push
          git tag "$tag"
          git push --tags

          echo "Released: $tag"
        env:
          RELEASE_BRANCH: ${{ inputs.release-branch }}
          RELEASE_TAG_PREFIX: ${{ inputs.release-tag-prefix }}

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.create-release.outputs.tag }}
