name: Example action
description: This is just an example action.

inputs:
  greeting:
    description: A greeting
    default: Hello!

outputs:
  greet-back:
    description: An answer

runs:
  using: node20
  main: index.mts
